Natural_Sum: Natural_Sum.o
	g++ Natural_Sum.o -o Natural_Sum

Natural_Sum.o: Natural_Sum.cpp
	g++ -c Natural_Sum.cpp -o Natural_Sum.o

run: Natural_Sum
	./Natural_Sum

clean:
	rm -f Natural_Sum.o Natural_Sum
