Quadratic_Equation: Quadratic_Equation.o
	g++ Quadratic_Equation.o -o Quadratic_Equation

Quadratic_Equation.o: Quadratic_Equation.cpp
	g++ -c Quadratic_Equation.cpp -o Quadratic_Equation.o

run: Quadratic_Equation
	./Quadratic_Equation

clean:
	rm -f Quadratic_Equation.o Quadratic_Equation